// Code generated by mockery. DO NOT EDIT.

package cluster

import (
	context "context"

	internalcluster "github.com/tochemey/goakt/v3/internal/cluster"
	internalpb "github.com/tochemey/goakt/v3/internal/internalpb"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// Cluster is an autogenerated mock type for the Cluster type
type Cluster struct {
	mock.Mock
}

type Cluster_Expecter struct {
	mock *mock.Mock
}

func (_m *Cluster) EXPECT() *Cluster_Expecter {
	return &Cluster_Expecter{mock: &_m.Mock}
}

// ActorExists provides a mock function with given fields: ctx, actorName
func (_m *Cluster) ActorExists(ctx context.Context, actorName string) (bool, error) {
	ret := _m.Called(ctx, actorName)

	if len(ret) == 0 {
		panic("no return value specified for ActorExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, actorName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, actorName)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, actorName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Cluster_ActorExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ActorExists'
type Cluster_ActorExists_Call struct {
	*mock.Call
}

// ActorExists is a helper method to define mock.On call
//   - ctx context.Context
//   - actorName string
func (_e *Cluster_Expecter) ActorExists(ctx interface{}, actorName interface{}) *Cluster_ActorExists_Call {
	return &Cluster_ActorExists_Call{Call: _e.mock.On("ActorExists", ctx, actorName)}
}

func (_c *Cluster_ActorExists_Call) Run(run func(ctx context.Context, actorName string)) *Cluster_ActorExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Cluster_ActorExists_Call) Return(_a0 bool, _a1 error) *Cluster_ActorExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Cluster_ActorExists_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *Cluster_ActorExists_Call {
	_c.Call.Return(run)
	return _c
}

// Actors provides a mock function with given fields: ctx, timeout
func (_m *Cluster) Actors(ctx context.Context, timeout time.Duration) ([]*internalpb.Actor, error) {
	ret := _m.Called(ctx, timeout)

	if len(ret) == 0 {
		panic("no return value specified for Actors")
	}

	var r0 []*internalpb.Actor
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Duration) ([]*internalpb.Actor, error)); ok {
		return rf(ctx, timeout)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Duration) []*internalpb.Actor); ok {
		r0 = rf(ctx, timeout)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*internalpb.Actor)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Duration) error); ok {
		r1 = rf(ctx, timeout)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Cluster_Actors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Actors'
type Cluster_Actors_Call struct {
	*mock.Call
}

// Actors is a helper method to define mock.On call
//   - ctx context.Context
//   - timeout time.Duration
func (_e *Cluster_Expecter) Actors(ctx interface{}, timeout interface{}) *Cluster_Actors_Call {
	return &Cluster_Actors_Call{Call: _e.mock.On("Actors", ctx, timeout)}
}

func (_c *Cluster_Actors_Call) Run(run func(ctx context.Context, timeout time.Duration)) *Cluster_Actors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Duration))
	})
	return _c
}

func (_c *Cluster_Actors_Call) Return(_a0 []*internalpb.Actor, _a1 error) *Cluster_Actors_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Cluster_Actors_Call) RunAndReturn(run func(context.Context, time.Duration) ([]*internalpb.Actor, error)) *Cluster_Actors_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteJobKey provides a mock function with given fields: ctx, jobID
func (_m *Cluster) DeleteJobKey(ctx context.Context, jobID string) error {
	ret := _m.Called(ctx, jobID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteJobKey")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, jobID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Cluster_DeleteJobKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteJobKey'
type Cluster_DeleteJobKey_Call struct {
	*mock.Call
}

// DeleteJobKey is a helper method to define mock.On call
//   - ctx context.Context
//   - jobID string
func (_e *Cluster_Expecter) DeleteJobKey(ctx interface{}, jobID interface{}) *Cluster_DeleteJobKey_Call {
	return &Cluster_DeleteJobKey_Call{Call: _e.mock.On("DeleteJobKey", ctx, jobID)}
}

func (_c *Cluster_DeleteJobKey_Call) Run(run func(ctx context.Context, jobID string)) *Cluster_DeleteJobKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Cluster_DeleteJobKey_Call) Return(_a0 error) *Cluster_DeleteJobKey_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Cluster_DeleteJobKey_Call) RunAndReturn(run func(context.Context, string) error) *Cluster_DeleteJobKey_Call {
	_c.Call.Return(run)
	return _c
}

// Events provides a mock function with no fields
func (_m *Cluster) Events() <-chan *internalcluster.Event {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Events")
	}

	var r0 <-chan *internalcluster.Event
	if rf, ok := ret.Get(0).(func() <-chan *internalcluster.Event); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *internalcluster.Event)
		}
	}

	return r0
}

// Cluster_Events_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Events'
type Cluster_Events_Call struct {
	*mock.Call
}

// Events is a helper method to define mock.On call
func (_e *Cluster_Expecter) Events() *Cluster_Events_Call {
	return &Cluster_Events_Call{Call: _e.mock.On("Events")}
}

func (_c *Cluster_Events_Call) Run(run func()) *Cluster_Events_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Cluster_Events_Call) Return(_a0 <-chan *internalcluster.Event) *Cluster_Events_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Cluster_Events_Call) RunAndReturn(run func() <-chan *internalcluster.Event) *Cluster_Events_Call {
	_c.Call.Return(run)
	return _c
}

// GetActor provides a mock function with given fields: ctx, actorName
func (_m *Cluster) GetActor(ctx context.Context, actorName string) (*internalpb.Actor, error) {
	ret := _m.Called(ctx, actorName)

	if len(ret) == 0 {
		panic("no return value specified for GetActor")
	}

	var r0 *internalpb.Actor
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*internalpb.Actor, error)); ok {
		return rf(ctx, actorName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *internalpb.Actor); ok {
		r0 = rf(ctx, actorName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*internalpb.Actor)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, actorName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Cluster_GetActor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActor'
type Cluster_GetActor_Call struct {
	*mock.Call
}

// GetActor is a helper method to define mock.On call
//   - ctx context.Context
//   - actorName string
func (_e *Cluster_Expecter) GetActor(ctx interface{}, actorName interface{}) *Cluster_GetActor_Call {
	return &Cluster_GetActor_Call{Call: _e.mock.On("GetActor", ctx, actorName)}
}

func (_c *Cluster_GetActor_Call) Run(run func(ctx context.Context, actorName string)) *Cluster_GetActor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Cluster_GetActor_Call) Return(_a0 *internalpb.Actor, _a1 error) *Cluster_GetActor_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Cluster_GetActor_Call) RunAndReturn(run func(context.Context, string) (*internalpb.Actor, error)) *Cluster_GetActor_Call {
	_c.Call.Return(run)
	return _c
}

// GetActorsByOwner provides a mock function with given fields: ctx, ownerNode
func (_m *Cluster) GetActorsByOwner(ctx context.Context, ownerNode string) ([]*internalpb.Actor, error) {
	ret := _m.Called(ctx, ownerNode)

	if len(ret) == 0 {
		panic("no return value specified for GetActorsByOwner")
	}

	var r0 []*internalpb.Actor
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*internalpb.Actor, error)); ok {
		return rf(ctx, ownerNode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*internalpb.Actor); ok {
		r0 = rf(ctx, ownerNode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*internalpb.Actor)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, ownerNode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Cluster_GetActorsByOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActorsByOwner'
type Cluster_GetActorsByOwner_Call struct {
	*mock.Call
}

// GetActorsByOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerNode string
func (_e *Cluster_Expecter) GetActorsByOwner(ctx interface{}, ownerNode interface{}) *Cluster_GetActorsByOwner_Call {
	return &Cluster_GetActorsByOwner_Call{Call: _e.mock.On("GetActorsByOwner", ctx, ownerNode)}
}

func (_c *Cluster_GetActorsByOwner_Call) Run(run func(ctx context.Context, ownerNode string)) *Cluster_GetActorsByOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Cluster_GetActorsByOwner_Call) Return(_a0 []*internalpb.Actor, _a1 error) *Cluster_GetActorsByOwner_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Cluster_GetActorsByOwner_Call) RunAndReturn(run func(context.Context, string) ([]*internalpb.Actor, error)) *Cluster_GetActorsByOwner_Call {
	_c.Call.Return(run)
	return _c
}

// GetGrain provides a mock function with given fields: ctx, identity
func (_m *Cluster) GetGrain(ctx context.Context, identity string) (*internalpb.Grain, error) {
	ret := _m.Called(ctx, identity)

	if len(ret) == 0 {
		panic("no return value specified for GetGrain")
	}

	var r0 *internalpb.Grain
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*internalpb.Grain, error)); ok {
		return rf(ctx, identity)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *internalpb.Grain); ok {
		r0 = rf(ctx, identity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*internalpb.Grain)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, identity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Cluster_GetGrain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGrain'
type Cluster_GetGrain_Call struct {
	*mock.Call
}

// GetGrain is a helper method to define mock.On call
//   - ctx context.Context
//   - identity string
func (_e *Cluster_Expecter) GetGrain(ctx interface{}, identity interface{}) *Cluster_GetGrain_Call {
	return &Cluster_GetGrain_Call{Call: _e.mock.On("GetGrain", ctx, identity)}
}

func (_c *Cluster_GetGrain_Call) Run(run func(ctx context.Context, identity string)) *Cluster_GetGrain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Cluster_GetGrain_Call) Return(_a0 *internalpb.Grain, _a1 error) *Cluster_GetGrain_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Cluster_GetGrain_Call) RunAndReturn(run func(context.Context, string) (*internalpb.Grain, error)) *Cluster_GetGrain_Call {
	_c.Call.Return(run)
	return _c
}

// GetGrainsByOwner provides a mock function with given fields: ctx, ownerNode
func (_m *Cluster) GetGrainsByOwner(ctx context.Context, ownerNode string) ([]*internalpb.Grain, error) {
	ret := _m.Called(ctx, ownerNode)

	if len(ret) == 0 {
		panic("no return value specified for GetGrainsByOwner")
	}

	var r0 []*internalpb.Grain
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*internalpb.Grain, error)); ok {
		return rf(ctx, ownerNode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*internalpb.Grain); ok {
		r0 = rf(ctx, ownerNode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*internalpb.Grain)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, ownerNode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Cluster_GetGrainsByOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGrainsByOwner'
type Cluster_GetGrainsByOwner_Call struct {
	*mock.Call
}

// GetGrainsByOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerNode string
func (_e *Cluster_Expecter) GetGrainsByOwner(ctx interface{}, ownerNode interface{}) *Cluster_GetGrainsByOwner_Call {
	return &Cluster_GetGrainsByOwner_Call{Call: _e.mock.On("GetGrainsByOwner", ctx, ownerNode)}
}

func (_c *Cluster_GetGrainsByOwner_Call) Run(run func(ctx context.Context, ownerNode string)) *Cluster_GetGrainsByOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Cluster_GetGrainsByOwner_Call) Return(_a0 []*internalpb.Grain, _a1 error) *Cluster_GetGrainsByOwner_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Cluster_GetGrainsByOwner_Call) RunAndReturn(run func(context.Context, string) ([]*internalpb.Grain, error)) *Cluster_GetGrainsByOwner_Call {
	_c.Call.Return(run)
	return _c
}

// GetPartition provides a mock function with given fields: actorName
func (_m *Cluster) GetPartition(actorName string) uint64 {
	ret := _m.Called(actorName)

	if len(ret) == 0 {
		panic("no return value specified for GetPartition")
	}

	var r0 uint64
	if rf, ok := ret.Get(0).(func(string) uint64); ok {
		r0 = rf(actorName)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	return r0
}

// Cluster_GetPartition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPartition'
type Cluster_GetPartition_Call struct {
	*mock.Call
}

// GetPartition is a helper method to define mock.On call
//   - actorName string
func (_e *Cluster_Expecter) GetPartition(actorName interface{}) *Cluster_GetPartition_Call {
	return &Cluster_GetPartition_Call{Call: _e.mock.On("GetPartition", actorName)}
}

func (_c *Cluster_GetPartition_Call) Run(run func(actorName string)) *Cluster_GetPartition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Cluster_GetPartition_Call) Return(_a0 uint64) *Cluster_GetPartition_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Cluster_GetPartition_Call) RunAndReturn(run func(string) uint64) *Cluster_GetPartition_Call {
	_c.Call.Return(run)
	return _c
}

// GrainExists provides a mock function with given fields: ctx, identity
func (_m *Cluster) GrainExists(ctx context.Context, identity string) (bool, error) {
	ret := _m.Called(ctx, identity)

	if len(ret) == 0 {
		panic("no return value specified for GrainExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, identity)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, identity)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, identity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Cluster_GrainExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GrainExists'
type Cluster_GrainExists_Call struct {
	*mock.Call
}

// GrainExists is a helper method to define mock.On call
//   - ctx context.Context
//   - identity string
func (_e *Cluster_Expecter) GrainExists(ctx interface{}, identity interface{}) *Cluster_GrainExists_Call {
	return &Cluster_GrainExists_Call{Call: _e.mock.On("GrainExists", ctx, identity)}
}

func (_c *Cluster_GrainExists_Call) Run(run func(ctx context.Context, identity string)) *Cluster_GrainExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Cluster_GrainExists_Call) Return(_a0 bool, _a1 error) *Cluster_GrainExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Cluster_GrainExists_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *Cluster_GrainExists_Call {
	_c.Call.Return(run)
	return _c
}

// Grains provides a mock function with given fields: ctx, timeout
func (_m *Cluster) Grains(ctx context.Context, timeout time.Duration) ([]*internalpb.Grain, error) {
	ret := _m.Called(ctx, timeout)

	if len(ret) == 0 {
		panic("no return value specified for Grains")
	}

	var r0 []*internalpb.Grain
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Duration) ([]*internalpb.Grain, error)); ok {
		return rf(ctx, timeout)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Duration) []*internalpb.Grain); ok {
		r0 = rf(ctx, timeout)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*internalpb.Grain)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Duration) error); ok {
		r1 = rf(ctx, timeout)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Cluster_Grains_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Grains'
type Cluster_Grains_Call struct {
	*mock.Call
}

// Grains is a helper method to define mock.On call
//   - ctx context.Context
//   - timeout time.Duration
func (_e *Cluster_Expecter) Grains(ctx interface{}, timeout interface{}) *Cluster_Grains_Call {
	return &Cluster_Grains_Call{Call: _e.mock.On("Grains", ctx, timeout)}
}

func (_c *Cluster_Grains_Call) Run(run func(ctx context.Context, timeout time.Duration)) *Cluster_Grains_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Duration))
	})
	return _c
}

func (_c *Cluster_Grains_Call) Return(_a0 []*internalpb.Grain, _a1 error) *Cluster_Grains_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Cluster_Grains_Call) RunAndReturn(run func(context.Context, time.Duration) ([]*internalpb.Grain, error)) *Cluster_Grains_Call {
	_c.Call.Return(run)
	return _c
}

// IsLeader provides a mock function with given fields: ctx
func (_m *Cluster) IsLeader(ctx context.Context) bool {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for IsLeader")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Cluster_IsLeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsLeader'
type Cluster_IsLeader_Call struct {
	*mock.Call
}

// IsLeader is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Cluster_Expecter) IsLeader(ctx interface{}) *Cluster_IsLeader_Call {
	return &Cluster_IsLeader_Call{Call: _e.mock.On("IsLeader", ctx)}
}

func (_c *Cluster_IsLeader_Call) Run(run func(ctx context.Context)) *Cluster_IsLeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Cluster_IsLeader_Call) Return(_a0 bool) *Cluster_IsLeader_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Cluster_IsLeader_Call) RunAndReturn(run func(context.Context) bool) *Cluster_IsLeader_Call {
	_c.Call.Return(run)
	return _c
}

// IsRunning provides a mock function with no fields
func (_m *Cluster) IsRunning() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsRunning")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Cluster_IsRunning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsRunning'
type Cluster_IsRunning_Call struct {
	*mock.Call
}

// IsRunning is a helper method to define mock.On call
func (_e *Cluster_Expecter) IsRunning() *Cluster_IsRunning_Call {
	return &Cluster_IsRunning_Call{Call: _e.mock.On("IsRunning")}
}

func (_c *Cluster_IsRunning_Call) Run(run func()) *Cluster_IsRunning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Cluster_IsRunning_Call) Return(_a0 bool) *Cluster_IsRunning_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Cluster_IsRunning_Call) RunAndReturn(run func() bool) *Cluster_IsRunning_Call {
	_c.Call.Return(run)
	return _c
}

// JobKey provides a mock function with given fields: ctx, jobID
func (_m *Cluster) JobKey(ctx context.Context, jobID string) ([]byte, error) {
	ret := _m.Called(ctx, jobID)

	if len(ret) == 0 {
		panic("no return value specified for JobKey")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return rf(ctx, jobID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = rf(ctx, jobID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, jobID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Cluster_JobKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JobKey'
type Cluster_JobKey_Call struct {
	*mock.Call
}

// JobKey is a helper method to define mock.On call
//   - ctx context.Context
//   - jobID string
func (_e *Cluster_Expecter) JobKey(ctx interface{}, jobID interface{}) *Cluster_JobKey_Call {
	return &Cluster_JobKey_Call{Call: _e.mock.On("JobKey", ctx, jobID)}
}

func (_c *Cluster_JobKey_Call) Run(run func(ctx context.Context, jobID string)) *Cluster_JobKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Cluster_JobKey_Call) Return(_a0 []byte, _a1 error) *Cluster_JobKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Cluster_JobKey_Call) RunAndReturn(run func(context.Context, string) ([]byte, error)) *Cluster_JobKey_Call {
	_c.Call.Return(run)
	return _c
}

// LookupKind provides a mock function with given fields: ctx, kind
func (_m *Cluster) LookupKind(ctx context.Context, kind string) (string, error) {
	ret := _m.Called(ctx, kind)

	if len(ret) == 0 {
		panic("no return value specified for LookupKind")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, kind)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, kind)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, kind)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Cluster_LookupKind_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LookupKind'
type Cluster_LookupKind_Call struct {
	*mock.Call
}

// LookupKind is a helper method to define mock.On call
//   - ctx context.Context
//   - kind string
func (_e *Cluster_Expecter) LookupKind(ctx interface{}, kind interface{}) *Cluster_LookupKind_Call {
	return &Cluster_LookupKind_Call{Call: _e.mock.On("LookupKind", ctx, kind)}
}

func (_c *Cluster_LookupKind_Call) Run(run func(ctx context.Context, kind string)) *Cluster_LookupKind_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Cluster_LookupKind_Call) Return(_a0 string, _a1 error) *Cluster_LookupKind_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Cluster_LookupKind_Call) RunAndReturn(run func(context.Context, string) (string, error)) *Cluster_LookupKind_Call {
	_c.Call.Return(run)
	return _c
}

// Members provides a mock function with given fields: ctx
func (_m *Cluster) Members(ctx context.Context) ([]*internalcluster.Peer, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Members")
	}

	var r0 []*internalcluster.Peer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*internalcluster.Peer, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*internalcluster.Peer); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*internalcluster.Peer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Cluster_Members_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Members'
type Cluster_Members_Call struct {
	*mock.Call
}

// Members is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Cluster_Expecter) Members(ctx interface{}) *Cluster_Members_Call {
	return &Cluster_Members_Call{Call: _e.mock.On("Members", ctx)}
}

func (_c *Cluster_Members_Call) Run(run func(ctx context.Context)) *Cluster_Members_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Cluster_Members_Call) Return(_a0 []*internalcluster.Peer, _a1 error) *Cluster_Members_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Cluster_Members_Call) RunAndReturn(run func(context.Context) ([]*internalcluster.Peer, error)) *Cluster_Members_Call {
	_c.Call.Return(run)
	return _c
}

// NextRoundRobinValue provides a mock function with given fields: ctx, key
func (_m *Cluster) NextRoundRobinValue(ctx context.Context, key string) (int, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for NextRoundRobinValue")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Cluster_NextRoundRobinValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NextRoundRobinValue'
type Cluster_NextRoundRobinValue_Call struct {
	*mock.Call
}

// NextRoundRobinValue is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *Cluster_Expecter) NextRoundRobinValue(ctx interface{}, key interface{}) *Cluster_NextRoundRobinValue_Call {
	return &Cluster_NextRoundRobinValue_Call{Call: _e.mock.On("NextRoundRobinValue", ctx, key)}
}

func (_c *Cluster_NextRoundRobinValue_Call) Run(run func(ctx context.Context, key string)) *Cluster_NextRoundRobinValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Cluster_NextRoundRobinValue_Call) Return(_a0 int, _a1 error) *Cluster_NextRoundRobinValue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Cluster_NextRoundRobinValue_Call) RunAndReturn(run func(context.Context, string) (int, error)) *Cluster_NextRoundRobinValue_Call {
	_c.Call.Return(run)
	return _c
}

// Peers provides a mock function with given fields: ctx
func (_m *Cluster) Peers(ctx context.Context) ([]*internalcluster.Peer, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Peers")
	}

	var r0 []*internalcluster.Peer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*internalcluster.Peer, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*internalcluster.Peer); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*internalcluster.Peer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Cluster_Peers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Peers'
type Cluster_Peers_Call struct {
	*mock.Call
}

// Peers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Cluster_Expecter) Peers(ctx interface{}) *Cluster_Peers_Call {
	return &Cluster_Peers_Call{Call: _e.mock.On("Peers", ctx)}
}

func (_c *Cluster_Peers_Call) Run(run func(ctx context.Context)) *Cluster_Peers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Cluster_Peers_Call) Return(_a0 []*internalcluster.Peer, _a1 error) *Cluster_Peers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Cluster_Peers_Call) RunAndReturn(run func(context.Context) ([]*internalcluster.Peer, error)) *Cluster_Peers_Call {
	_c.Call.Return(run)
	return _c
}

// PutActor provides a mock function with given fields: ctx, actor
func (_m *Cluster) PutActor(ctx context.Context, actor *internalpb.Actor) error {
	ret := _m.Called(ctx, actor)

	if len(ret) == 0 {
		panic("no return value specified for PutActor")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *internalpb.Actor) error); ok {
		r0 = rf(ctx, actor)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Cluster_PutActor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutActor'
type Cluster_PutActor_Call struct {
	*mock.Call
}

// PutActor is a helper method to define mock.On call
//   - ctx context.Context
//   - actor *internalpb.Actor
func (_e *Cluster_Expecter) PutActor(ctx interface{}, actor interface{}) *Cluster_PutActor_Call {
	return &Cluster_PutActor_Call{Call: _e.mock.On("PutActor", ctx, actor)}
}

func (_c *Cluster_PutActor_Call) Run(run func(ctx context.Context, actor *internalpb.Actor)) *Cluster_PutActor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*internalpb.Actor))
	})
	return _c
}

func (_c *Cluster_PutActor_Call) Return(_a0 error) *Cluster_PutActor_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Cluster_PutActor_Call) RunAndReturn(run func(context.Context, *internalpb.Actor) error) *Cluster_PutActor_Call {
	_c.Call.Return(run)
	return _c
}

// PutGrain provides a mock function with given fields: ctx, grain
func (_m *Cluster) PutGrain(ctx context.Context, grain *internalpb.Grain) error {
	ret := _m.Called(ctx, grain)

	if len(ret) == 0 {
		panic("no return value specified for PutGrain")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *internalpb.Grain) error); ok {
		r0 = rf(ctx, grain)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Cluster_PutGrain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutGrain'
type Cluster_PutGrain_Call struct {
	*mock.Call
}

// PutGrain is a helper method to define mock.On call
//   - ctx context.Context
//   - grain *internalpb.Grain
func (_e *Cluster_Expecter) PutGrain(ctx interface{}, grain interface{}) *Cluster_PutGrain_Call {
	return &Cluster_PutGrain_Call{Call: _e.mock.On("PutGrain", ctx, grain)}
}

func (_c *Cluster_PutGrain_Call) Run(run func(ctx context.Context, grain *internalpb.Grain)) *Cluster_PutGrain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*internalpb.Grain))
	})
	return _c
}

func (_c *Cluster_PutGrain_Call) Return(_a0 error) *Cluster_PutGrain_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Cluster_PutGrain_Call) RunAndReturn(run func(context.Context, *internalpb.Grain) error) *Cluster_PutGrain_Call {
	_c.Call.Return(run)
	return _c
}

// PutJobKey provides a mock function with given fields: ctx, jobID, metadata
func (_m *Cluster) PutJobKey(ctx context.Context, jobID string, metadata []byte) error {
	ret := _m.Called(ctx, jobID, metadata)

	if len(ret) == 0 {
		panic("no return value specified for PutJobKey")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) error); ok {
		r0 = rf(ctx, jobID, metadata)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Cluster_PutJobKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutJobKey'
type Cluster_PutJobKey_Call struct {
	*mock.Call
}

// PutJobKey is a helper method to define mock.On call
//   - ctx context.Context
//   - jobID string
//   - metadata []byte
func (_e *Cluster_Expecter) PutJobKey(ctx interface{}, jobID interface{}, metadata interface{}) *Cluster_PutJobKey_Call {
	return &Cluster_PutJobKey_Call{Call: _e.mock.On("PutJobKey", ctx, jobID, metadata)}
}

func (_c *Cluster_PutJobKey_Call) Run(run func(ctx context.Context, jobID string, metadata []byte)) *Cluster_PutJobKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte))
	})
	return _c
}

func (_c *Cluster_PutJobKey_Call) Return(_a0 error) *Cluster_PutJobKey_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Cluster_PutJobKey_Call) RunAndReturn(run func(context.Context, string, []byte) error) *Cluster_PutJobKey_Call {
	_c.Call.Return(run)
	return _c
}

// PutKind provides a mock function with given fields: ctx, kind
func (_m *Cluster) PutKind(ctx context.Context, kind string) error {
	ret := _m.Called(ctx, kind)

	if len(ret) == 0 {
		panic("no return value specified for PutKind")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, kind)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Cluster_PutKind_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutKind'
type Cluster_PutKind_Call struct {
	*mock.Call
}

// PutKind is a helper method to define mock.On call
//   - ctx context.Context
//   - kind string
func (_e *Cluster_Expecter) PutKind(ctx interface{}, kind interface{}) *Cluster_PutKind_Call {
	return &Cluster_PutKind_Call{Call: _e.mock.On("PutKind", ctx, kind)}
}

func (_c *Cluster_PutKind_Call) Run(run func(ctx context.Context, kind string)) *Cluster_PutKind_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Cluster_PutKind_Call) Return(_a0 error) *Cluster_PutKind_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Cluster_PutKind_Call) RunAndReturn(run func(context.Context, string) error) *Cluster_PutKind_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveActor provides a mock function with given fields: ctx, actorName
func (_m *Cluster) RemoveActor(ctx context.Context, actorName string) error {
	ret := _m.Called(ctx, actorName)

	if len(ret) == 0 {
		panic("no return value specified for RemoveActor")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, actorName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Cluster_RemoveActor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveActor'
type Cluster_RemoveActor_Call struct {
	*mock.Call
}

// RemoveActor is a helper method to define mock.On call
//   - ctx context.Context
//   - actorName string
func (_e *Cluster_Expecter) RemoveActor(ctx interface{}, actorName interface{}) *Cluster_RemoveActor_Call {
	return &Cluster_RemoveActor_Call{Call: _e.mock.On("RemoveActor", ctx, actorName)}
}

func (_c *Cluster_RemoveActor_Call) Run(run func(ctx context.Context, actorName string)) *Cluster_RemoveActor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Cluster_RemoveActor_Call) Return(_a0 error) *Cluster_RemoveActor_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Cluster_RemoveActor_Call) RunAndReturn(run func(context.Context, string) error) *Cluster_RemoveActor_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveGrain provides a mock function with given fields: ctx, identity
func (_m *Cluster) RemoveGrain(ctx context.Context, identity string) error {
	ret := _m.Called(ctx, identity)

	if len(ret) == 0 {
		panic("no return value specified for RemoveGrain")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, identity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Cluster_RemoveGrain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveGrain'
type Cluster_RemoveGrain_Call struct {
	*mock.Call
}

// RemoveGrain is a helper method to define mock.On call
//   - ctx context.Context
//   - identity string
func (_e *Cluster_Expecter) RemoveGrain(ctx interface{}, identity interface{}) *Cluster_RemoveGrain_Call {
	return &Cluster_RemoveGrain_Call{Call: _e.mock.On("RemoveGrain", ctx, identity)}
}

func (_c *Cluster_RemoveGrain_Call) Run(run func(ctx context.Context, identity string)) *Cluster_RemoveGrain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Cluster_RemoveGrain_Call) Return(_a0 error) *Cluster_RemoveGrain_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Cluster_RemoveGrain_Call) RunAndReturn(run func(context.Context, string) error) *Cluster_RemoveGrain_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveKind provides a mock function with given fields: ctx, kind
func (_m *Cluster) RemoveKind(ctx context.Context, kind string) error {
	ret := _m.Called(ctx, kind)

	if len(ret) == 0 {
		panic("no return value specified for RemoveKind")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, kind)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Cluster_RemoveKind_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveKind'
type Cluster_RemoveKind_Call struct {
	*mock.Call
}

// RemoveKind is a helper method to define mock.On call
//   - ctx context.Context
//   - kind string
func (_e *Cluster_Expecter) RemoveKind(ctx interface{}, kind interface{}) *Cluster_RemoveKind_Call {
	return &Cluster_RemoveKind_Call{Call: _e.mock.On("RemoveKind", ctx, kind)}
}

func (_c *Cluster_RemoveKind_Call) Run(run func(ctx context.Context, kind string)) *Cluster_RemoveKind_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Cluster_RemoveKind_Call) Return(_a0 error) *Cluster_RemoveKind_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Cluster_RemoveKind_Call) RunAndReturn(run func(context.Context, string) error) *Cluster_RemoveKind_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function with given fields: ctx
func (_m *Cluster) Start(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Cluster_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type Cluster_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Cluster_Expecter) Start(ctx interface{}) *Cluster_Start_Call {
	return &Cluster_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *Cluster_Start_Call) Run(run func(ctx context.Context)) *Cluster_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Cluster_Start_Call) Return(_a0 error) *Cluster_Start_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Cluster_Start_Call) RunAndReturn(run func(context.Context) error) *Cluster_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function with given fields: ctx
func (_m *Cluster) Stop(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Cluster_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type Cluster_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Cluster_Expecter) Stop(ctx interface{}) *Cluster_Stop_Call {
	return &Cluster_Stop_Call{Call: _e.mock.On("Stop", ctx)}
}

func (_c *Cluster_Stop_Call) Run(run func(ctx context.Context)) *Cluster_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Cluster_Stop_Call) Return(_a0 error) *Cluster_Stop_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Cluster_Stop_Call) RunAndReturn(run func(context.Context) error) *Cluster_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// NewCluster creates a new instance of Cluster. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCluster(t interface {
	mock.TestingT
	Cleanup(func())
}) *Cluster {
	mock := &Cluster{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
