# https://docs.codecov.com/docs/codecov-yaml
  coverage:
    status:
      patch:
          default:
              target: 90%
    project:
        default:
            target: 80%    # the required coverage value
            threshold: 1%  # the leniency in hitting the target
  ignore:
    - "pb/**/*"
    - "test/**/*"
    - "examples/**/*"
    - "internal/**/*"
    - "testkit/**/*"
