quiet: False
disable-version-string: True
with-expecter: True
exported: True
filename: "{{ .InterfaceName | snakecase }}.go"
outpkg: mocks
packages:
  github.com/tochemey/goakt/v2/hash:
    config:
    interfaces:
      Hasher:
        config:
          dir: hash
  github.com/tochemey/goakt/v2/discovery:
    config:
    interfaces:
      Provider:
        config:
          dir: discovery
  github.com/tochemey/goakt/v2/internal/cluster:
    config:
    interfaces:
      Interface:
        config:
          dir: cluster