# https://docs.codecov.com/docs/codecov-yaml
coverage:
  status:
    patch:
      default:
        target: 80%
    project:
      default:
        target: 80%    # the required coverage value
        base: auto
ignore:
  - "test"
  - "internal/internalpb"
  - "testkit"
  - "mocks"
  - "goaktpb"
