services:
  accounts:
    image: "accounts:dev"
    deploy:
      mode: replicated
      replicas: 3
    command:
      - run
    ports:
      - "50051"
      - "9092"
    environment:
      SERVICE_NAME: accounts
      SYSTEM_NAME: AccountsSystem
      PORT: 50051
      GOSSIP_PORT: 3322
      PEERS_PORT: 3320
      REMOTING_PORT: 50052
