// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: internal/handshake.proto

package internalpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LaneRole identifies the role of a duplex connection within the per-peer
// lane set negotiated at HELLO time.
type LaneRole int32

const (
	LaneRole_LANE_ROLE_CONTROL  LaneRole = 0
	LaneRole_LANE_ROLE_ORDINARY LaneRole = 1
	LaneRole_LANE_ROLE_LARGE    LaneRole = 2
)

// Enum value maps for LaneRole.
var (
	LaneRole_name = map[int32]string{
		0: "LANE_ROLE_CONTROL",
		1: "LANE_ROLE_ORDINARY",
		2: "LANE_ROLE_LARGE",
	}
	LaneRole_value = map[string]int32{
		"LANE_ROLE_CONTROL":  0,
		"LANE_ROLE_ORDINARY": 1,
		"LANE_ROLE_LARGE":    2,
	}
)

func (x LaneRole) Enum() *LaneRole {
	p := new(LaneRole)
	*p = x
	return p
}

func (x LaneRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LaneRole) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_handshake_proto_enumTypes[0].Descriptor()
}

func (LaneRole) Type() protoreflect.EnumType {
	return &file_internal_handshake_proto_enumTypes[0]
}

func (x LaneRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// CompressionCodec is the whole-connection compression wrapper negotiated
// during the duplex handshake. Both peers wrap the connection only after
// HELLO/HELLO_ACK completes.
type CompressionCodec int32

const (
	CompressionCodec_COMPRESSION_CODEC_NONE   CompressionCodec = 0
	CompressionCodec_COMPRESSION_CODEC_GZIP   CompressionCodec = 1
	CompressionCodec_COMPRESSION_CODEC_ZSTD   CompressionCodec = 2
	CompressionCodec_COMPRESSION_CODEC_BROTLI CompressionCodec = 3
)

// Enum value maps for CompressionCodec.
var (
	CompressionCodec_name = map[int32]string{
		0: "COMPRESSION_CODEC_NONE",
		1: "COMPRESSION_CODEC_GZIP",
		2: "COMPRESSION_CODEC_ZSTD",
		3: "COMPRESSION_CODEC_BROTLI",
	}
	CompressionCodec_value = map[string]int32{
		"COMPRESSION_CODEC_NONE":   0,
		"COMPRESSION_CODEC_GZIP":   1,
		"COMPRESSION_CODEC_ZSTD":   2,
		"COMPRESSION_CODEC_BROTLI": 3,
	}
)

func (x CompressionCodec) Enum() *CompressionCodec {
	p := new(CompressionCodec)
	*p = x
	return p
}

func (x CompressionCodec) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CompressionCodec) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_handshake_proto_enumTypes[1].Descriptor()
}

func (CompressionCodec) Type() protoreflect.EnumType {
	return &file_internal_handshake_proto_enumTypes[1]
}

func (x CompressionCodec) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Hello is the payload of HELLO and HELLO_ACK frames on the duplex protocol.
// Effective limits are the pairwise minimum of the dialer and acceptor values.
type Hello struct {
	state                                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Revision                    uint32                 `protobuf:"varint,1,opt,name=revision,proto3"`
	xxx_hidden_SystemName                  string                 `protobuf:"bytes,2,opt,name=system_name,json=systemName,proto3"`
	xxx_hidden_Host                        string                 `protobuf:"bytes,3,opt,name=host,proto3"`
	xxx_hidden_Port                        uint32                 `protobuf:"varint,4,opt,name=port,proto3"`
	xxx_hidden_LaneRole                    LaneRole               `protobuf:"varint,5,opt,name=lane_role,json=laneRole,proto3,enum=internalpb.LaneRole"`
	xxx_hidden_LaneIndex                   uint32                 `protobuf:"varint,6,opt,name=lane_index,json=laneIndex,proto3"`
	xxx_hidden_Compression                 CompressionCodec       `protobuf:"varint,7,opt,name=compression,proto3,enum=internalpb.CompressionCodec"`
	xxx_hidden_MaxFrameSize                uint32                 `protobuf:"varint,8,opt,name=max_frame_size,json=maxFrameSize,proto3"`
	xxx_hidden_MaxMessageSize              uint64                 `protobuf:"varint,9,opt,name=max_message_size,json=maxMessageSize,proto3"`
	xxx_hidden_InitialCredits              uint64                 `protobuf:"varint,10,opt,name=initial_credits,json=initialCredits,proto3"`
	xxx_hidden_MaxConcurrentLargeTransfers uint32                 `protobuf:"varint,11,opt,name=max_concurrent_large_transfers,json=maxConcurrentLargeTransfers,proto3"`
	unknownFields                          protoimpl.UnknownFields
	sizeCache                              protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_internal_handshake_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_internal_handshake_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Hello) GetRevision() uint32 {
	if x != nil {
		return x.xxx_hidden_Revision
	}
	return 0
}

func (x *Hello) GetSystemName() string {
	if x != nil {
		return x.xxx_hidden_SystemName
	}
	return ""
}

func (x *Hello) GetHost() string {
	if x != nil {
		return x.xxx_hidden_Host
	}
	return ""
}

func (x *Hello) GetPort() uint32 {
	if x != nil {
		return x.xxx_hidden_Port
	}
	return 0
}

func (x *Hello) GetLaneRole() LaneRole {
	if x != nil {
		return x.xxx_hidden_LaneRole
	}
	return LaneRole_LANE_ROLE_CONTROL
}

func (x *Hello) GetLaneIndex() uint32 {
	if x != nil {
		return x.xxx_hidden_LaneIndex
	}
	return 0
}

func (x *Hello) GetCompression() CompressionCodec {
	if x != nil {
		return x.xxx_hidden_Compression
	}
	return CompressionCodec_COMPRESSION_CODEC_NONE
}

func (x *Hello) GetMaxFrameSize() uint32 {
	if x != nil {
		return x.xxx_hidden_MaxFrameSize
	}
	return 0
}

func (x *Hello) GetMaxMessageSize() uint64 {
	if x != nil {
		return x.xxx_hidden_MaxMessageSize
	}
	return 0
}

func (x *Hello) GetInitialCredits() uint64 {
	if x != nil {
		return x.xxx_hidden_InitialCredits
	}
	return 0
}

func (x *Hello) GetMaxConcurrentLargeTransfers() uint32 {
	if x != nil {
		return x.xxx_hidden_MaxConcurrentLargeTransfers
	}
	return 0
}

func (x *Hello) SetRevision(v uint32) {
	x.xxx_hidden_Revision = v
}

func (x *Hello) SetSystemName(v string) {
	x.xxx_hidden_SystemName = v
}

func (x *Hello) SetHost(v string) {
	x.xxx_hidden_Host = v
}

func (x *Hello) SetPort(v uint32) {
	x.xxx_hidden_Port = v
}

func (x *Hello) SetLaneRole(v LaneRole) {
	x.xxx_hidden_LaneRole = v
}

func (x *Hello) SetLaneIndex(v uint32) {
	x.xxx_hidden_LaneIndex = v
}

func (x *Hello) SetCompression(v CompressionCodec) {
	x.xxx_hidden_Compression = v
}

func (x *Hello) SetMaxFrameSize(v uint32) {
	x.xxx_hidden_MaxFrameSize = v
}

func (x *Hello) SetMaxMessageSize(v uint64) {
	x.xxx_hidden_MaxMessageSize = v
}

func (x *Hello) SetInitialCredits(v uint64) {
	x.xxx_hidden_InitialCredits = v
}

func (x *Hello) SetMaxConcurrentLargeTransfers(v uint32) {
	x.xxx_hidden_MaxConcurrentLargeTransfers = v
}

type Hello_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Capability revision. Cumulative: 1 = baseline DATA/REPLY/ERROR/PING/PONG,
	// 2 = chunking, 3 = compression tables, 4 = credit-based flow control.
	Revision uint32
	// Actor system name of the sending node.
	SystemName string
	// Advertised host of the sending node.
	Host string
	// Advertised remoting port of the sending node.
	Port uint32
	// Role of this connection within the peer lane set.
	LaneRole LaneRole
	// Index within the role (meaningful for ordinary lanes).
	LaneIndex uint32
	// Proposed (dialer) or selected (acceptor) compression codec.
	Compression CompressionCodec
	// Largest frame payload the sender is willing to accept.
	MaxFrameSize uint32
	// Largest reassembled message the sender is willing to accept.
	MaxMessageSize uint64
	// Initial credit window in bytes proposed by the sender.
	InitialCredits uint64
	// Maximum concurrent chunk reassembly groups the sender will hold.
	MaxConcurrentLargeTransfers uint32
}

func (b0 Hello_builder) Build() *Hello {
	m0 := &Hello{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Revision = b.Revision
	x.xxx_hidden_SystemName = b.SystemName
	x.xxx_hidden_Host = b.Host
	x.xxx_hidden_Port = b.Port
	x.xxx_hidden_LaneRole = b.LaneRole
	x.xxx_hidden_LaneIndex = b.LaneIndex
	x.xxx_hidden_Compression = b.Compression
	x.xxx_hidden_MaxFrameSize = b.MaxFrameSize
	x.xxx_hidden_MaxMessageSize = b.MaxMessageSize
	x.xxx_hidden_InitialCredits = b.InitialCredits
	x.xxx_hidden_MaxConcurrentLargeTransfers = b.MaxConcurrentLargeTransfers
	return m0
}

var File_internal_handshake_proto protoreflect.FileDescriptor

const file_internal_handshake_proto_rawDesc = "" +
	"\n" +
	"\x18internal/handshake.proto\x12\n" +
	"internalpb\"\xbc\x03\n" +
	"\x05Hello\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\rR\brevision\x12\x1f\n" +
	"\vsystem_name\x18\x02 \x01(\tR\n" +
	"systemName\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x04 \x01(\rR\x04port\x121\n" +
	"\tlane_role\x18\x05 \x01(\x0e2\x14.internalpb.LaneRoleR\blaneRole\x12\x1d\n" +
	"\n" +
	"lane_index\x18\x06 \x01(\rR\tlaneIndex\x12>\n" +
	"\vcompression\x18\a \x01(\x0e2\x1c.internalpb.CompressionCodecR\vcompression\x12$\n" +
	"\x0emax_frame_size\x18\b \x01(\rR\fmaxFrameSize\x12(\n" +
	"\x10max_message_size\x18\t \x01(\x04R\x0emaxMessageSize\x12'\n" +
	"\x0finitial_credits\x18\n" +
	" \x01(\x04R\x0einitialCredits\x12C\n" +
	"\x1emax_concurrent_large_transfers\x18\v \x01(\rR\x1bmaxConcurrentLargeTransfers*N\n" +
	"\bLaneRole\x12\x15\n" +
	"\x11LANE_ROLE_CONTROL\x10\x00\x12\x16\n" +
	"\x12LANE_ROLE_ORDINARY\x10\x01\x12\x13\n" +
	"\x0fLANE_ROLE_LARGE\x10\x02*\x84\x01\n" +
	"\x10CompressionCodec\x12\x1a\n" +
	"\x16COMPRESSION_CODEC_NONE\x10\x00\x12\x1a\n" +
	"\x16COMPRESSION_CODEC_GZIP\x10\x01\x12\x1a\n" +
	"\x16COMPRESSION_CODEC_ZSTD\x10\x02\x12\x1c\n" +
	"\x18COMPRESSION_CODEC_BROTLI\x10\x03B\xa7\x01\n" +
	"\x0ecom.internalpbB\x0eHandshakeProtoH\x02P\x01Z;github.com/tochemey/goakt/v4/internal/internalpb;internalpb\xa2\x02\x03IXX\xaa\x02\n" +
	"Internalpb\xca\x02\n" +
	"Internalpb\xe2\x02\x16Internalpb\\GPBMetadata\xea\x02\n" +
	"Internalpbb\x06proto3"

var file_internal_handshake_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_internal_handshake_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_handshake_proto_goTypes = []any{
	(LaneRole)(0),         // 0: internalpb.LaneRole
	(CompressionCodec)(0), // 1: internalpb.CompressionCodec
	(*Hello)(nil),         // 2: internalpb.Hello
}
var file_internal_handshake_proto_depIdxs = []int32{
	0, // 0: internalpb.Hello.lane_role:type_name -> internalpb.LaneRole
	1, // 1: internalpb.Hello.compression:type_name -> internalpb.CompressionCodec
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_handshake_proto_init() }
func file_internal_handshake_proto_init() {
	if File_internal_handshake_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_handshake_proto_rawDesc), len(file_internal_handshake_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_handshake_proto_goTypes,
		DependencyIndexes: file_internal_handshake_proto_depIdxs,
		EnumInfos:         file_internal_handshake_proto_enumTypes,
		MessageInfos:      file_internal_handshake_proto_msgTypes,
	}.Build()
	File_internal_handshake_proto = out.File
	file_internal_handshake_proto_goTypes = nil
	file_internal_handshake_proto_depIdxs = nil
}
