// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: internal/metric.proto

package internalpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Metric struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Uptime                  int64                  `protobuf:"varint,1,opt,name=uptime,proto3" json:"uptime,omitempty"`
	LatestProcessedDuration *durationpb.Duration   `protobuf:"bytes,2,opt,name=latest_processed_duration,json=latestProcessedDuration,proto3" json:"latest_processed_duration,omitempty"`
	ChildrenCount           uint64                 `protobuf:"varint,3,opt,name=children_count,json=childrenCount,proto3" json:"children_count,omitempty"`
	DeadlettersCount        uint64                 `protobuf:"varint,4,opt,name=deadletters_count,json=deadlettersCount,proto3" json:"deadletters_count,omitempty"`
	RestartCount            uint64                 `protobuf:"varint,5,opt,name=restart_count,json=restartCount,proto3" json:"restart_count,omitempty"`
	ProcessedCount          uint64                 `protobuf:"varint,6,opt,name=processed_count,json=processedCount,proto3" json:"processed_count,omitempty"`
	StashSize               uint64                 `protobuf:"varint,7,opt,name=stash_size,json=stashSize,proto3" json:"stash_size,omitempty"`
	FailureCount            uint64                 `protobuf:"varint,8,opt,name=failure_count,json=failureCount,proto3" json:"failure_count,omitempty"`
	ReinstateCount          uint64                 `protobuf:"varint,9,opt,name=reinstate_count,json=reinstateCount,proto3" json:"reinstate_count,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_internal_metric_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_internal_metric_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_internal_metric_proto_rawDescGZIP(), []int{0}
}

func (x *Metric) GetUptime() int64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

func (x *Metric) GetLatestProcessedDuration() *durationpb.Duration {
	if x != nil {
		return x.LatestProcessedDuration
	}
	return nil
}

func (x *Metric) GetChildrenCount() uint64 {
	if x != nil {
		return x.ChildrenCount
	}
	return 0
}

func (x *Metric) GetDeadlettersCount() uint64 {
	if x != nil {
		return x.DeadlettersCount
	}
	return 0
}

func (x *Metric) GetRestartCount() uint64 {
	if x != nil {
		return x.RestartCount
	}
	return 0
}

func (x *Metric) GetProcessedCount() uint64 {
	if x != nil {
		return x.ProcessedCount
	}
	return 0
}

func (x *Metric) GetStashSize() uint64 {
	if x != nil {
		return x.StashSize
	}
	return 0
}

func (x *Metric) GetFailureCount() uint64 {
	if x != nil {
		return x.FailureCount
	}
	return 0
}

func (x *Metric) GetReinstateCount() uint64 {
	if x != nil {
		return x.ReinstateCount
	}
	return 0
}

var File_internal_metric_proto protoreflect.FileDescriptor

const file_internal_metric_proto_rawDesc = "" +
	"\n" +
	"\x15internal/metric.proto\x12\n" +
	"internalpb\x1a\x1egoogle/protobuf/duration.proto\"\x86\x03\n" +
	"\x06Metric\x12\x16\n" +
	"\x06uptime\x18\x01 \x01(\x03R\x06uptime\x12U\n" +
	"\x19latest_processed_duration\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x17latestProcessedDuration\x12%\n" +
	"\x0echildren_count\x18\x03 \x01(\x04R\rchildrenCount\x12+\n" +
	"\x11deadletters_count\x18\x04 \x01(\x04R\x10deadlettersCount\x12#\n" +
	"\rrestart_count\x18\x05 \x01(\x04R\frestartCount\x12'\n" +
	"\x0fprocessed_count\x18\x06 \x01(\x04R\x0eprocessedCount\x12\x1d\n" +
	"\n" +
	"stash_size\x18\a \x01(\x04R\tstashSize\x12#\n" +
	"\rfailure_count\x18\b \x01(\x04R\ffailureCount\x12'\n" +
	"\x0freinstate_count\x18\t \x01(\x04R\x0ereinstateCountB\xa4\x01\n" +
	"\x0ecom.internalpbB\vMetricProtoH\x02P\x01Z;github.com/tochemey/goakt/v4/internal/internalpb;internalpb\xa2\x02\x03IXX\xaa\x02\n" +
	"Internalpb\xca\x02\n" +
	"Internalpb\xe2\x02\x16Internalpb\\GPBMetadata\xea\x02\n" +
	"Internalpbb\x06proto3"

var (
	file_internal_metric_proto_rawDescOnce sync.Once
	file_internal_metric_proto_rawDescData []byte
)

func file_internal_metric_proto_rawDescGZIP() []byte {
	file_internal_metric_proto_rawDescOnce.Do(func() {
		file_internal_metric_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_metric_proto_rawDesc), len(file_internal_metric_proto_rawDesc)))
	})
	return file_internal_metric_proto_rawDescData
}

var file_internal_metric_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_metric_proto_goTypes = []any{
	(*Metric)(nil),              // 0: internalpb.Metric
	(*durationpb.Duration)(nil), // 1: google.protobuf.Duration
}
var file_internal_metric_proto_depIdxs = []int32{
	1, // 0: internalpb.Metric.latest_processed_duration:type_name -> google.protobuf.Duration
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_metric_proto_init() }
func file_internal_metric_proto_init() {
	if File_internal_metric_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_metric_proto_rawDesc), len(file_internal_metric_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_metric_proto_goTypes,
		DependencyIndexes: file_internal_metric_proto_depIdxs,
		MessageInfos:      file_internal_metric_proto_msgTypes,
	}.Build()
	File_internal_metric_proto = out.File
	file_internal_metric_proto_goTypes = nil
	file_internal_metric_proto_depIdxs = nil
}
