// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: internal/peers.proto

package internalpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PeerState struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Host         string                 `protobuf:"bytes,1,opt,name=host,proto3"`
	xxx_hidden_RemotingPort int32                  `protobuf:"varint,2,opt,name=remoting_port,json=remotingPort,proto3"`
	xxx_hidden_PeersPort    int32                  `protobuf:"varint,3,opt,name=peers_port,json=peersPort,proto3"`
	xxx_hidden_Actors       map[string]*Actor      `protobuf:"bytes,4,rep,name=actors,proto3" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_Grains       map[string]*Grain      `protobuf:"bytes,5,rep,name=grains,proto3" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *PeerState) Reset() {
	*x = PeerState{}
	mi := &file_internal_peers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerState) ProtoMessage() {}

func (x *PeerState) ProtoReflect() protoreflect.Message {
	mi := &file_internal_peers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PeerState) GetHost() string {
	if x != nil {
		return x.xxx_hidden_Host
	}
	return ""
}

func (x *PeerState) GetRemotingPort() int32 {
	if x != nil {
		return x.xxx_hidden_RemotingPort
	}
	return 0
}

func (x *PeerState) GetPeersPort() int32 {
	if x != nil {
		return x.xxx_hidden_PeersPort
	}
	return 0
}

func (x *PeerState) GetActors() map[string]*Actor {
	if x != nil {
		return x.xxx_hidden_Actors
	}
	return nil
}

func (x *PeerState) GetGrains() map[string]*Grain {
	if x != nil {
		return x.xxx_hidden_Grains
	}
	return nil
}

func (x *PeerState) SetHost(v string) {
	x.xxx_hidden_Host = v
}

func (x *PeerState) SetRemotingPort(v int32) {
	x.xxx_hidden_RemotingPort = v
}

func (x *PeerState) SetPeersPort(v int32) {
	x.xxx_hidden_PeersPort = v
}

func (x *PeerState) SetActors(v map[string]*Actor) {
	x.xxx_hidden_Actors = v
}

func (x *PeerState) SetGrains(v map[string]*Grain) {
	x.xxx_hidden_Grains = v
}

type PeerState_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Specifies the peer host
	Host string
	// Specifies the remoting port
	RemotingPort int32
	// Specifies the remoting host
	PeersPort int32
	// Specifies the list of actors
	// actorName -> Actor
	Actors map[string]*Actor
	// grainId -> Grain
	Grains map[string]*Grain
}

func (b0 PeerState_builder) Build() *PeerState {
	m0 := &PeerState{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Host = b.Host
	x.xxx_hidden_RemotingPort = b.RemotingPort
	x.xxx_hidden_PeersPort = b.PeersPort
	x.xxx_hidden_Actors = b.Actors
	x.xxx_hidden_Grains = b.Grains
	return m0
}

type Rebalance struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_PeerState *PeerState             `protobuf:"bytes,1,opt,name=peer_state,json=peerState,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Rebalance) Reset() {
	*x = Rebalance{}
	mi := &file_internal_peers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rebalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rebalance) ProtoMessage() {}

func (x *Rebalance) ProtoReflect() protoreflect.Message {
	mi := &file_internal_peers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Rebalance) GetPeerState() *PeerState {
	if x != nil {
		return x.xxx_hidden_PeerState
	}
	return nil
}

func (x *Rebalance) SetPeerState(v *PeerState) {
	x.xxx_hidden_PeerState = v
}

func (x *Rebalance) HasPeerState() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_PeerState != nil
}

func (x *Rebalance) ClearPeerState() {
	x.xxx_hidden_PeerState = nil
}

type Rebalance_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Specifies the peer state
	PeerState *PeerState
}

func (b0 Rebalance_builder) Build() *Rebalance {
	m0 := &Rebalance{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_PeerState = b.PeerState
	return m0
}

type RebalanceComplete struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_PeerAddress string                 `protobuf:"bytes,1,opt,name=peer_address,json=peerAddress,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RebalanceComplete) Reset() {
	*x = RebalanceComplete{}
	mi := &file_internal_peers_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebalanceComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebalanceComplete) ProtoMessage() {}

func (x *RebalanceComplete) ProtoReflect() protoreflect.Message {
	mi := &file_internal_peers_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RebalanceComplete) GetPeerAddress() string {
	if x != nil {
		return x.xxx_hidden_PeerAddress
	}
	return ""
}

func (x *RebalanceComplete) SetPeerAddress(v string) {
	x.xxx_hidden_PeerAddress = v
}

type RebalanceComplete_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Specifies the peer address
	PeerAddress string
}

func (b0 RebalanceComplete_builder) Build() *RebalanceComplete {
	m0 := &RebalanceComplete{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_PeerAddress = b.PeerAddress
	return m0
}

// RelocateBatchRequest carries one target peer's share of a departed node's
// actors and grains, relocated in a single round trip.
type RelocateBatchRequest struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_DepartedNode string                 `protobuf:"bytes,1,opt,name=departed_node,json=departedNode,proto3"`
	xxx_hidden_Actors       *[]*Actor              `protobuf:"bytes,2,rep,name=actors,proto3"`
	xxx_hidden_Grains       *[]*Grain              `protobuf:"bytes,3,rep,name=grains,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *RelocateBatchRequest) Reset() {
	*x = RelocateBatchRequest{}
	mi := &file_internal_peers_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelocateBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelocateBatchRequest) ProtoMessage() {}

func (x *RelocateBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_peers_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RelocateBatchRequest) GetDepartedNode() string {
	if x != nil {
		return x.xxx_hidden_DepartedNode
	}
	return ""
}

func (x *RelocateBatchRequest) GetActors() []*Actor {
	if x != nil {
		if x.xxx_hidden_Actors != nil {
			return *x.xxx_hidden_Actors
		}
	}
	return nil
}

func (x *RelocateBatchRequest) GetGrains() []*Grain {
	if x != nil {
		if x.xxx_hidden_Grains != nil {
			return *x.xxx_hidden_Grains
		}
	}
	return nil
}

func (x *RelocateBatchRequest) SetDepartedNode(v string) {
	x.xxx_hidden_DepartedNode = v
}

func (x *RelocateBatchRequest) SetActors(v []*Actor) {
	x.xxx_hidden_Actors = &v
}

func (x *RelocateBatchRequest) SetGrains(v []*Grain) {
	x.xxx_hidden_Grains = &v
}

type RelocateBatchRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Specifies the remoting address (host:remoting_port) of the node that left
	// the cluster. The target uses it to clean up stale registry entries that
	// still point at the departed node before recreating the relocated actors
	// and grains.
	DepartedNode string
	// Specifies the actors to recreate on the target node
	Actors []*Actor
	// Specifies the grains to relocate on the target node. The target dispatches
	// on each grain's eager_relocation flag: eager grains are reactivated
	// upfront, lazy grains (the default) only have their directory entry
	// released so they re-activate on next use.
	Grains []*Grain
}

func (b0 RelocateBatchRequest_builder) Build() *RelocateBatchRequest {
	m0 := &RelocateBatchRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_DepartedNode = b.DepartedNode
	x.xxx_hidden_Actors = &b.Actors
	x.xxx_hidden_Grains = &b.Grains
	return m0
}

// RelocateBatchResponse reports per-item relocation failures.
// An empty list means the whole batch was relocated successfully.
type RelocateBatchResponse struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Failures *[]*RelocationFailure  `protobuf:"bytes,1,rep,name=failures,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RelocateBatchResponse) Reset() {
	*x = RelocateBatchResponse{}
	mi := &file_internal_peers_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelocateBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelocateBatchResponse) ProtoMessage() {}

func (x *RelocateBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_peers_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RelocateBatchResponse) GetFailures() []*RelocationFailure {
	if x != nil {
		if x.xxx_hidden_Failures != nil {
			return *x.xxx_hidden_Failures
		}
	}
	return nil
}

func (x *RelocateBatchResponse) SetFailures(v []*RelocationFailure) {
	x.xxx_hidden_Failures = &v
}

type RelocateBatchResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Specifies the items that could not be relocated
	Failures []*RelocationFailure
}

func (b0 RelocateBatchResponse_builder) Build() *RelocateBatchResponse {
	m0 := &RelocateBatchResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Failures = &b.Failures
	return m0
}

// RelocationFailure describes a single actor or grain that could not be
// relocated as part of a RelocateBatchRequest.
type RelocationFailure struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id      string                 `protobuf:"bytes,1,opt,name=id,proto3"`
	xxx_hidden_Grain   bool                   `protobuf:"varint,2,opt,name=grain,proto3"`
	xxx_hidden_Message string                 `protobuf:"bytes,3,opt,name=message,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RelocationFailure) Reset() {
	*x = RelocationFailure{}
	mi := &file_internal_peers_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelocationFailure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelocationFailure) ProtoMessage() {}

func (x *RelocationFailure) ProtoReflect() protoreflect.Message {
	mi := &file_internal_peers_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RelocationFailure) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *RelocationFailure) GetGrain() bool {
	if x != nil {
		return x.xxx_hidden_Grain
	}
	return false
}

func (x *RelocationFailure) GetMessage() string {
	if x != nil {
		return x.xxx_hidden_Message
	}
	return ""
}

func (x *RelocationFailure) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *RelocationFailure) SetGrain(v bool) {
	x.xxx_hidden_Grain = v
}

func (x *RelocationFailure) SetMessage(v string) {
	x.xxx_hidden_Message = v
}

type RelocationFailure_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Specifies the actor address or the grain identity string
	Id string
	// Specifies whether the failed item is a grain
	Grain bool
	// Specifies the failure reason
	Message string
}

func (b0 RelocationFailure_builder) Build() *RelocationFailure {
	m0 := &RelocationFailure{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Grain = b.Grain
	x.xxx_hidden_Message = b.Message
	return m0
}

type PersistPeerActor struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Host         string                 `protobuf:"bytes,1,opt,name=host,proto3"`
	xxx_hidden_RemotingPort int32                  `protobuf:"varint,2,opt,name=remoting_port,json=remotingPort,proto3"`
	xxx_hidden_PeersPort    int32                  `protobuf:"varint,3,opt,name=peers_port,json=peersPort,proto3"`
	xxx_hidden_Actor        *Actor                 `protobuf:"bytes,4,opt,name=actor,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *PersistPeerActor) Reset() {
	*x = PersistPeerActor{}
	mi := &file_internal_peers_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersistPeerActor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersistPeerActor) ProtoMessage() {}

func (x *PersistPeerActor) ProtoReflect() protoreflect.Message {
	mi := &file_internal_peers_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PersistPeerActor) GetHost() string {
	if x != nil {
		return x.xxx_hidden_Host
	}
	return ""
}

func (x *PersistPeerActor) GetRemotingPort() int32 {
	if x != nil {
		return x.xxx_hidden_RemotingPort
	}
	return 0
}

func (x *PersistPeerActor) GetPeersPort() int32 {
	if x != nil {
		return x.xxx_hidden_PeersPort
	}
	return 0
}

func (x *PersistPeerActor) GetActor() *Actor {
	if x != nil {
		return x.xxx_hidden_Actor
	}
	return nil
}

func (x *PersistPeerActor) SetHost(v string) {
	x.xxx_hidden_Host = v
}

func (x *PersistPeerActor) SetRemotingPort(v int32) {
	x.xxx_hidden_RemotingPort = v
}

func (x *PersistPeerActor) SetPeersPort(v int32) {
	x.xxx_hidden_PeersPort = v
}

func (x *PersistPeerActor) SetActor(v *Actor) {
	x.xxx_hidden_Actor = v
}

func (x *PersistPeerActor) HasActor() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Actor != nil
}

func (x *PersistPeerActor) ClearActor() {
	x.xxx_hidden_Actor = nil
}

type PersistPeerActor_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Specifies the peer host
	Host string
	// Specifies the remoting port
	RemotingPort int32
	// Specifies the remoting host
	PeersPort int32
	// Specifies the actor
	Actor *Actor
}

func (b0 PersistPeerActor_builder) Build() *PersistPeerActor {
	m0 := &PersistPeerActor{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Host = b.Host
	x.xxx_hidden_RemotingPort = b.RemotingPort
	x.xxx_hidden_PeersPort = b.PeersPort
	x.xxx_hidden_Actor = b.Actor
	return m0
}

type PersistPeerGrain struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Host         string                 `protobuf:"bytes,1,opt,name=host,proto3"`
	xxx_hidden_RemotingPort int32                  `protobuf:"varint,2,opt,name=remoting_port,json=remotingPort,proto3"`
	xxx_hidden_PeersPort    int32                  `protobuf:"varint,3,opt,name=peers_port,json=peersPort,proto3"`
	xxx_hidden_Grain        *Grain                 `protobuf:"bytes,4,opt,name=grain,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *PersistPeerGrain) Reset() {
	*x = PersistPeerGrain{}
	mi := &file_internal_peers_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersistPeerGrain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersistPeerGrain) ProtoMessage() {}

func (x *PersistPeerGrain) ProtoReflect() protoreflect.Message {
	mi := &file_internal_peers_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PersistPeerGrain) GetHost() string {
	if x != nil {
		return x.xxx_hidden_Host
	}
	return ""
}

func (x *PersistPeerGrain) GetRemotingPort() int32 {
	if x != nil {
		return x.xxx_hidden_RemotingPort
	}
	return 0
}

func (x *PersistPeerGrain) GetPeersPort() int32 {
	if x != nil {
		return x.xxx_hidden_PeersPort
	}
	return 0
}

func (x *PersistPeerGrain) GetGrain() *Grain {
	if x != nil {
		return x.xxx_hidden_Grain
	}
	return nil
}

func (x *PersistPeerGrain) SetHost(v string) {
	x.xxx_hidden_Host = v
}

func (x *PersistPeerGrain) SetRemotingPort(v int32) {
	x.xxx_hidden_RemotingPort = v
}

func (x *PersistPeerGrain) SetPeersPort(v int32) {
	x.xxx_hidden_PeersPort = v
}

func (x *PersistPeerGrain) SetGrain(v *Grain) {
	x.xxx_hidden_Grain = v
}

func (x *PersistPeerGrain) HasGrain() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Grain != nil
}

func (x *PersistPeerGrain) ClearGrain() {
	x.xxx_hidden_Grain = nil
}

type PersistPeerGrain_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Specifies the peer host
	Host string
	// Specifies the remoting port
	RemotingPort int32
	// Specifies the remoting host
	PeersPort int32
	// Specifies the grain
	Grain *Grain
}

func (b0 PersistPeerGrain_builder) Build() *PersistPeerGrain {
	m0 := &PersistPeerGrain{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Host = b.Host
	x.xxx_hidden_RemotingPort = b.RemotingPort
	x.xxx_hidden_PeersPort = b.PeersPort
	x.xxx_hidden_Grain = b.Grain
	return m0
}

type RemovePeerActor struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_PeerAddress string                 `protobuf:"bytes,1,opt,name=peer_address,json=peerAddress,proto3"`
	xxx_hidden_ActorName   string                 `protobuf:"bytes,2,opt,name=actor_name,json=actorName,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RemovePeerActor) Reset() {
	*x = RemovePeerActor{}
	mi := &file_internal_peers_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePeerActor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePeerActor) ProtoMessage() {}

func (x *RemovePeerActor) ProtoReflect() protoreflect.Message {
	mi := &file_internal_peers_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RemovePeerActor) GetPeerAddress() string {
	if x != nil {
		return x.xxx_hidden_PeerAddress
	}
	return ""
}

func (x *RemovePeerActor) GetActorName() string {
	if x != nil {
		return x.xxx_hidden_ActorName
	}
	return ""
}

func (x *RemovePeerActor) SetPeerAddress(v string) {
	x.xxx_hidden_PeerAddress = v
}

func (x *RemovePeerActor) SetActorName(v string) {
	x.xxx_hidden_ActorName = v
}

type RemovePeerActor_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Specifies the peer address
	PeerAddress string
	// Specifies the remoting por
	// Specifies the actor name
	ActorName string
}

func (b0 RemovePeerActor_builder) Build() *RemovePeerActor {
	m0 := &RemovePeerActor{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_PeerAddress = b.PeerAddress
	x.xxx_hidden_ActorName = b.ActorName
	return m0
}

type RemovePeerGrain struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_PeerAddress string                 `protobuf:"bytes,1,opt,name=peer_address,json=peerAddress,proto3"`
	xxx_hidden_GrainId     *GrainId               `protobuf:"bytes,2,opt,name=grain_id,json=grainId,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RemovePeerGrain) Reset() {
	*x = RemovePeerGrain{}
	mi := &file_internal_peers_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePeerGrain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePeerGrain) ProtoMessage() {}

func (x *RemovePeerGrain) ProtoReflect() protoreflect.Message {
	mi := &file_internal_peers_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RemovePeerGrain) GetPeerAddress() string {
	if x != nil {
		return x.xxx_hidden_PeerAddress
	}
	return ""
}

func (x *RemovePeerGrain) GetGrainId() *GrainId {
	if x != nil {
		return x.xxx_hidden_GrainId
	}
	return nil
}

func (x *RemovePeerGrain) SetPeerAddress(v string) {
	x.xxx_hidden_PeerAddress = v
}

func (x *RemovePeerGrain) SetGrainId(v *GrainId) {
	x.xxx_hidden_GrainId = v
}

func (x *RemovePeerGrain) HasGrainId() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_GrainId != nil
}

func (x *RemovePeerGrain) ClearGrainId() {
	x.xxx_hidden_GrainId = nil
}

type RemovePeerGrain_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Specifies the peer address
	PeerAddress string
	GrainId     *GrainId
}

func (b0 RemovePeerGrain_builder) Build() *RemovePeerGrain {
	m0 := &RemovePeerGrain{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_PeerAddress = b.PeerAddress
	x.xxx_hidden_GrainId = b.GrainId
	return m0
}

type GetPeerState struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_PeerAddress string                 `protobuf:"bytes,1,opt,name=peer_address,json=peerAddress,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetPeerState) Reset() {
	*x = GetPeerState{}
	mi := &file_internal_peers_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPeerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeerState) ProtoMessage() {}

func (x *GetPeerState) ProtoReflect() protoreflect.Message {
	mi := &file_internal_peers_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetPeerState) GetPeerAddress() string {
	if x != nil {
		return x.xxx_hidden_PeerAddress
	}
	return ""
}

func (x *GetPeerState) SetPeerAddress(v string) {
	x.xxx_hidden_PeerAddress = v
}

type GetPeerState_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Specifies the peer address
	PeerAddress string
}

func (b0 GetPeerState_builder) Build() *GetPeerState {
	m0 := &GetPeerState{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_PeerAddress = b.PeerAddress
	return m0
}

type DeletePeerState struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_PeerAddress string                 `protobuf:"bytes,1,opt,name=peer_address,json=peerAddress,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DeletePeerState) Reset() {
	*x = DeletePeerState{}
	mi := &file_internal_peers_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePeerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePeerState) ProtoMessage() {}

func (x *DeletePeerState) ProtoReflect() protoreflect.Message {
	mi := &file_internal_peers_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeletePeerState) GetPeerAddress() string {
	if x != nil {
		return x.xxx_hidden_PeerAddress
	}
	return ""
}

func (x *DeletePeerState) SetPeerAddress(v string) {
	x.xxx_hidden_PeerAddress = v
}

type DeletePeerState_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Specifies the peer address
	PeerAddress string
}

func (b0 DeletePeerState_builder) Build() *DeletePeerState {
	m0 := &DeletePeerState{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_PeerAddress = b.PeerAddress
	return m0
}

var File_internal_peers_proto protoreflect.FileDescriptor

const file_internal_peers_proto_rawDesc = "" +
	"\n" +
	"\x14internal/peers.proto\x12\n" +
	"internalpb\x1a\x14internal/actor.proto\x1a\x14internal/grain.proto\"\xf5\x02\n" +
	"\tPeerState\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12#\n" +
	"\rremoting_port\x18\x02 \x01(\x05R\fremotingPort\x12\x1d\n" +
	"\n" +
	"peers_port\x18\x03 \x01(\x05R\tpeersPort\x129\n" +
	"\x06actors\x18\x04 \x03(\v2!.internalpb.PeerState.ActorsEntryR\x06actors\x129\n" +
	"\x06grains\x18\x05 \x03(\v2!.internalpb.PeerState.GrainsEntryR\x06grains\x1aL\n" +
	"\vActorsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.internalpb.ActorR\x05value:\x028\x01\x1aL\n" +
	"\vGrainsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.internalpb.GrainR\x05value:\x028\x01\"A\n" +
	"\tRebalance\x124\n" +
	"\n" +
	"peer_state\x18\x01 \x01(\v2\x15.internalpb.PeerStateR\tpeerState\"6\n" +
	"\x11RebalanceComplete\x12!\n" +
	"\fpeer_address\x18\x01 \x01(\tR\vpeerAddress\"\x91\x01\n" +
	"\x14RelocateBatchRequest\x12#\n" +
	"\rdeparted_node\x18\x01 \x01(\tR\fdepartedNode\x12)\n" +
	"\x06actors\x18\x02 \x03(\v2\x11.internalpb.ActorR\x06actors\x12)\n" +
	"\x06grains\x18\x03 \x03(\v2\x11.internalpb.GrainR\x06grains\"R\n" +
	"\x15RelocateBatchResponse\x129\n" +
	"\bfailures\x18\x01 \x03(\v2\x1d.internalpb.RelocationFailureR\bfailures\"S\n" +
	"\x11RelocationFailure\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05grain\x18\x02 \x01(\bR\x05grain\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x93\x01\n" +
	"\x10PersistPeerActor\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12#\n" +
	"\rremoting_port\x18\x02 \x01(\x05R\fremotingPort\x12\x1d\n" +
	"\n" +
	"peers_port\x18\x03 \x01(\x05R\tpeersPort\x12'\n" +
	"\x05actor\x18\x04 \x01(\v2\x11.internalpb.ActorR\x05actor\"\x93\x01\n" +
	"\x10PersistPeerGrain\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12#\n" +
	"\rremoting_port\x18\x02 \x01(\x05R\fremotingPort\x12\x1d\n" +
	"\n" +
	"peers_port\x18\x03 \x01(\x05R\tpeersPort\x12'\n" +
	"\x05grain\x18\x04 \x01(\v2\x11.internalpb.GrainR\x05grain\"S\n" +
	"\x0fRemovePeerActor\x12!\n" +
	"\fpeer_address\x18\x01 \x01(\tR\vpeerAddress\x12\x1d\n" +
	"\n" +
	"actor_name\x18\x02 \x01(\tR\tactorName\"d\n" +
	"\x0fRemovePeerGrain\x12!\n" +
	"\fpeer_address\x18\x01 \x01(\tR\vpeerAddress\x12.\n" +
	"\bgrain_id\x18\x02 \x01(\v2\x13.internalpb.GrainIdR\agrainId\"1\n" +
	"\fGetPeerState\x12!\n" +
	"\fpeer_address\x18\x01 \x01(\tR\vpeerAddress\"4\n" +
	"\x0fDeletePeerState\x12!\n" +
	"\fpeer_address\x18\x01 \x01(\tR\vpeerAddressB\xa3\x01\n" +
	"\x0ecom.internalpbB\n" +
	"PeersProtoH\x02P\x01Z;github.com/tochemey/goakt/v4/internal/internalpb;internalpb\xa2\x02\x03IXX\xaa\x02\n" +
	"Internalpb\xca\x02\n" +
	"Internalpb\xe2\x02\x16Internalpb\\GPBMetadata\xea\x02\n" +
	"Internalpbb\x06proto3"

var file_internal_peers_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_internal_peers_proto_goTypes = []any{
	(*PeerState)(nil),             // 0: internalpb.PeerState
	(*Rebalance)(nil),             // 1: internalpb.Rebalance
	(*RebalanceComplete)(nil),     // 2: internalpb.RebalanceComplete
	(*RelocateBatchRequest)(nil),  // 3: internalpb.RelocateBatchRequest
	(*RelocateBatchResponse)(nil), // 4: internalpb.RelocateBatchResponse
	(*RelocationFailure)(nil),     // 5: internalpb.RelocationFailure
	(*PersistPeerActor)(nil),      // 6: internalpb.PersistPeerActor
	(*PersistPeerGrain)(nil),      // 7: internalpb.PersistPeerGrain
	(*RemovePeerActor)(nil),       // 8: internalpb.RemovePeerActor
	(*RemovePeerGrain)(nil),       // 9: internalpb.RemovePeerGrain
	(*GetPeerState)(nil),          // 10: internalpb.GetPeerState
	(*DeletePeerState)(nil),       // 11: internalpb.DeletePeerState
	nil,                           // 12: internalpb.PeerState.ActorsEntry
	nil,                           // 13: internalpb.PeerState.GrainsEntry
	(*Actor)(nil),                 // 14: internalpb.Actor
	(*Grain)(nil),                 // 15: internalpb.Grain
	(*GrainId)(nil),               // 16: internalpb.GrainId
}
var file_internal_peers_proto_depIdxs = []int32{
	12, // 0: internalpb.PeerState.actors:type_name -> internalpb.PeerState.ActorsEntry
	13, // 1: internalpb.PeerState.grains:type_name -> internalpb.PeerState.GrainsEntry
	0,  // 2: internalpb.Rebalance.peer_state:type_name -> internalpb.PeerState
	14, // 3: internalpb.RelocateBatchRequest.actors:type_name -> internalpb.Actor
	15, // 4: internalpb.RelocateBatchRequest.grains:type_name -> internalpb.Grain
	5,  // 5: internalpb.RelocateBatchResponse.failures:type_name -> internalpb.RelocationFailure
	14, // 6: internalpb.PersistPeerActor.actor:type_name -> internalpb.Actor
	15, // 7: internalpb.PersistPeerGrain.grain:type_name -> internalpb.Grain
	16, // 8: internalpb.RemovePeerGrain.grain_id:type_name -> internalpb.GrainId
	14, // 9: internalpb.PeerState.ActorsEntry.value:type_name -> internalpb.Actor
	15, // 10: internalpb.PeerState.GrainsEntry.value:type_name -> internalpb.Grain
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_internal_peers_proto_init() }
func file_internal_peers_proto_init() {
	if File_internal_peers_proto != nil {
		return
	}
	file_internal_actor_proto_init()
	file_internal_grain_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_peers_proto_rawDesc), len(file_internal_peers_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_peers_proto_goTypes,
		DependencyIndexes: file_internal_peers_proto_depIdxs,
		MessageInfos:      file_internal_peers_proto_msgTypes,
	}.Build()
	File_internal_peers_proto = out.File
	file_internal_peers_proto_goTypes = nil
	file_internal_peers_proto_depIdxs = nil
}
