// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: internal/supervision.proto

package internalpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Strategy int32

const (
	Strategy_STRATEGY_ONE_FOR_ONE Strategy = 0
	Strategy_STRATEGY_ONE_FOR_ALL Strategy = 1
)

// Enum value maps for Strategy.
var (
	Strategy_name = map[int32]string{
		0: "STRATEGY_ONE_FOR_ONE",
		1: "STRATEGY_ONE_FOR_ALL",
	}
	Strategy_value = map[string]int32{
		"STRATEGY_ONE_FOR_ONE": 0,
		"STRATEGY_ONE_FOR_ALL": 1,
	}
)

func (x Strategy) Enum() *Strategy {
	p := new(Strategy)
	*p = x
	return p
}

func (x Strategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Strategy) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_supervision_proto_enumTypes[0].Descriptor()
}

func (Strategy) Type() protoreflect.EnumType {
	return &file_internal_supervision_proto_enumTypes[0]
}

func (x Strategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Strategy.Descriptor instead.
func (Strategy) EnumDescriptor() ([]byte, []int) {
	return file_internal_supervision_proto_rawDescGZIP(), []int{0}
}

// Mayday message is sent by a child
// actor to its parent when it is panicking or returning an error
// while processing messages
type Mayday struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Specifies the actor id
	ActorId string `protobuf:"bytes,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	// Specifies the error message
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Specifies the directive
	//
	// Types that are valid to be assigned to Directive:
	//
	//	*Mayday_Stop
	//	*Mayday_Resume
	//	*Mayday_Restart
	//	*Mayday_Escalate
	Directive isMayday_Directive `protobuf_oneof:"directive"`
	// Specifies the strategy
	Strategy      Strategy `protobuf:"varint,7,opt,name=strategy,proto3,enum=internalpb.Strategy" json:"strategy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mayday) Reset() {
	*x = Mayday{}
	mi := &file_internal_supervision_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mayday) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mayday) ProtoMessage() {}

func (x *Mayday) ProtoReflect() protoreflect.Message {
	mi := &file_internal_supervision_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mayday.ProtoReflect.Descriptor instead.
func (*Mayday) Descriptor() ([]byte, []int) {
	return file_internal_supervision_proto_rawDescGZIP(), []int{0}
}

func (x *Mayday) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *Mayday) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *Mayday) GetDirective() isMayday_Directive {
	if x != nil {
		return x.Directive
	}
	return nil
}

func (x *Mayday) GetStop() *StopDirective {
	if x != nil {
		if x, ok := x.Directive.(*Mayday_Stop); ok {
			return x.Stop
		}
	}
	return nil
}

func (x *Mayday) GetResume() *ResumeDirective {
	if x != nil {
		if x, ok := x.Directive.(*Mayday_Resume); ok {
			return x.Resume
		}
	}
	return nil
}

func (x *Mayday) GetRestart() *RestartDirective {
	if x != nil {
		if x, ok := x.Directive.(*Mayday_Restart); ok {
			return x.Restart
		}
	}
	return nil
}

func (x *Mayday) GetEscalate() *EscalateDirective {
	if x != nil {
		if x, ok := x.Directive.(*Mayday_Escalate); ok {
			return x.Escalate
		}
	}
	return nil
}

func (x *Mayday) GetStrategy() Strategy {
	if x != nil {
		return x.Strategy
	}
	return Strategy_STRATEGY_ONE_FOR_ONE
}

type isMayday_Directive interface {
	isMayday_Directive()
}

type Mayday_Stop struct {
	Stop *StopDirective `protobuf:"bytes,3,opt,name=stop,proto3,oneof"`
}

type Mayday_Resume struct {
	Resume *ResumeDirective `protobuf:"bytes,4,opt,name=resume,proto3,oneof"`
}

type Mayday_Restart struct {
	Restart *RestartDirective `protobuf:"bytes,5,opt,name=restart,proto3,oneof"`
}

type Mayday_Escalate struct {
	Escalate *EscalateDirective `protobuf:"bytes,6,opt,name=escalate,proto3,oneof"`
}

func (*Mayday_Stop) isMayday_Directive() {}

func (*Mayday_Resume) isMayday_Directive() {}

func (*Mayday_Restart) isMayday_Directive() {}

func (*Mayday_Escalate) isMayday_Directive() {}

// StopDirective defines the supervisor stop directive
type StopDirective struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopDirective) Reset() {
	*x = StopDirective{}
	mi := &file_internal_supervision_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopDirective) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopDirective) ProtoMessage() {}

func (x *StopDirective) ProtoReflect() protoreflect.Message {
	mi := &file_internal_supervision_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopDirective.ProtoReflect.Descriptor instead.
func (*StopDirective) Descriptor() ([]byte, []int) {
	return file_internal_supervision_proto_rawDescGZIP(), []int{1}
}

// ResumeDirective defines the supervisor resume directive
// This ignores the failure and processes the next message, instead
type ResumeDirective struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeDirective) Reset() {
	*x = ResumeDirective{}
	mi := &file_internal_supervision_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeDirective) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeDirective) ProtoMessage() {}

func (x *ResumeDirective) ProtoReflect() protoreflect.Message {
	mi := &file_internal_supervision_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeDirective.ProtoReflect.Descriptor instead.
func (*ResumeDirective) Descriptor() ([]byte, []int) {
	return file_internal_supervision_proto_rawDescGZIP(), []int{2}
}

// EscalateDirective defines the supervisor escalation directive
// It escalates the failure to the next parent in the hierarchy, thereby failing itself
type EscalateDirective struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EscalateDirective) Reset() {
	*x = EscalateDirective{}
	mi := &file_internal_supervision_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EscalateDirective) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EscalateDirective) ProtoMessage() {}

func (x *EscalateDirective) ProtoReflect() protoreflect.Message {
	mi := &file_internal_supervision_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EscalateDirective.ProtoReflect.Descriptor instead.
func (*EscalateDirective) Descriptor() ([]byte, []int) {
	return file_internal_supervision_proto_rawDescGZIP(), []int{3}
}

// RestartDirective defines supervisor restart directive
type RestartDirective struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Specifies the maximum number of retries;
	// When reaching this number, the faulty actor is stopped
	MaxRetries uint32 `protobuf:"varint,1,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	// Specifies the time range to restart the faulty actor
	Timeout       int64 `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartDirective) Reset() {
	*x = RestartDirective{}
	mi := &file_internal_supervision_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartDirective) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartDirective) ProtoMessage() {}

func (x *RestartDirective) ProtoReflect() protoreflect.Message {
	mi := &file_internal_supervision_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartDirective.ProtoReflect.Descriptor instead.
func (*RestartDirective) Descriptor() ([]byte, []int) {
	return file_internal_supervision_proto_rawDescGZIP(), []int{4}
}

func (x *RestartDirective) GetMaxRetries() uint32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *RestartDirective) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

var File_internal_supervision_proto protoreflect.FileDescriptor

const file_internal_supervision_proto_rawDesc = "" +
	"\n" +
	"\x1ainternal/supervision.proto\x12\n" +
	"internalpb\"\xe6\x02\n" +
	"\x06Mayday\x12\x19\n" +
	"\bactor_id\x18\x01 \x01(\tR\aactorId\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12/\n" +
	"\x04stop\x18\x03 \x01(\v2\x19.internalpb.StopDirectiveH\x00R\x04stop\x125\n" +
	"\x06resume\x18\x04 \x01(\v2\x1b.internalpb.ResumeDirectiveH\x00R\x06resume\x128\n" +
	"\arestart\x18\x05 \x01(\v2\x1c.internalpb.RestartDirectiveH\x00R\arestart\x12;\n" +
	"\bescalate\x18\x06 \x01(\v2\x1d.internalpb.EscalateDirectiveH\x00R\bescalate\x120\n" +
	"\bstrategy\x18\a \x01(\x0e2\x14.internalpb.StrategyR\bstrategyB\v\n" +
	"\tdirective\"\x0f\n" +
	"\rStopDirective\"\x11\n" +
	"\x0fResumeDirective\"\x13\n" +
	"\x11EscalateDirective\"M\n" +
	"\x10RestartDirective\x12\x1f\n" +
	"\vmax_retries\x18\x01 \x01(\rR\n" +
	"maxRetries\x12\x18\n" +
	"\atimeout\x18\x02 \x01(\x03R\atimeout*>\n" +
	"\bStrategy\x12\x18\n" +
	"\x14STRATEGY_ONE_FOR_ONE\x10\x00\x12\x18\n" +
	"\x14STRATEGY_ONE_FOR_ALL\x10\x01B\xa9\x01\n" +
	"\x0ecom.internalpbB\x10SupervisionProtoH\x02P\x01Z;github.com/tochemey/goakt/v3/internal/internalpb;internalpb\xa2\x02\x03IXX\xaa\x02\n" +
	"Internalpb\xca\x02\n" +
	"Internalpb\xe2\x02\x16Internalpb\\GPBMetadata\xea\x02\n" +
	"Internalpbb\x06proto3"

var (
	file_internal_supervision_proto_rawDescOnce sync.Once
	file_internal_supervision_proto_rawDescData []byte
)

func file_internal_supervision_proto_rawDescGZIP() []byte {
	file_internal_supervision_proto_rawDescOnce.Do(func() {
		file_internal_supervision_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_supervision_proto_rawDesc), len(file_internal_supervision_proto_rawDesc)))
	})
	return file_internal_supervision_proto_rawDescData
}

var file_internal_supervision_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_supervision_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_supervision_proto_goTypes = []any{
	(Strategy)(0),             // 0: internalpb.Strategy
	(*Mayday)(nil),            // 1: internalpb.Mayday
	(*StopDirective)(nil),     // 2: internalpb.StopDirective
	(*ResumeDirective)(nil),   // 3: internalpb.ResumeDirective
	(*EscalateDirective)(nil), // 4: internalpb.EscalateDirective
	(*RestartDirective)(nil),  // 5: internalpb.RestartDirective
}
var file_internal_supervision_proto_depIdxs = []int32{
	2, // 0: internalpb.Mayday.stop:type_name -> internalpb.StopDirective
	3, // 1: internalpb.Mayday.resume:type_name -> internalpb.ResumeDirective
	5, // 2: internalpb.Mayday.restart:type_name -> internalpb.RestartDirective
	4, // 3: internalpb.Mayday.escalate:type_name -> internalpb.EscalateDirective
	0, // 4: internalpb.Mayday.strategy:type_name -> internalpb.Strategy
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_internal_supervision_proto_init() }
func file_internal_supervision_proto_init() {
	if File_internal_supervision_proto != nil {
		return
	}
	file_internal_supervision_proto_msgTypes[0].OneofWrappers = []any{
		(*Mayday_Stop)(nil),
		(*Mayday_Resume)(nil),
		(*Mayday_Restart)(nil),
		(*Mayday_Escalate)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_supervision_proto_rawDesc), len(file_internal_supervision_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_supervision_proto_goTypes,
		DependencyIndexes: file_internal_supervision_proto_depIdxs,
		EnumInfos:         file_internal_supervision_proto_enumTypes,
		MessageInfos:      file_internal_supervision_proto_msgTypes,
	}.Build()
	File_internal_supervision_proto = out.File
	file_internal_supervision_proto_goTypes = nil
	file_internal_supervision_proto_depIdxs = nil
}
